server:
  port: 8080
  compression:
    enabled: true
spring:
  application:
    name: webcare
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=webcare
    username: sa
    password: root
  jmx:
    default-domain: webcare
  thymeleaf:
    enabled: true
    check-template-location: true
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: elvinjava1@gmail.com
    password: bEtk4Gyp4brtfZsO5tUO

pemits:
  url: http://localhost:4200/


